### ISSUE TITLE
运行环境报错

### ISSUE THREAD

**Issue by ch3n90** [petterobam/html2file#1]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by petterobam** [comment]
抱歉，才看到，这个是SpringBoot项目，提示错误是没有找到org.springframework.context.ApplicationContext这个类，你应该是打开项目的时候没有识别到maven项目，或者没有加载响应的maven依赖，导致某些类没有加载到，可以百度一下自行处理：maven项目导入【你用的IDE名字】

**Comment by ibbbb** [comment]
I fixed it  half a year ago
